### ISSUE TITLE
Unexpected file 'change' events on directory creation.

### ISSUE THREAD

**Issue by arubtsov** [paulmillr/chokidar#499] opened 2016-06-15 16:45 UTC
I'm on Windows 8.1 x64, node v4.4.5 \ v.6.1.0 , Chokidar 1.5.2.
Problem occurs only on Win platform.

When creating a directory, 'change' events fire for files (at the same level) whose paths include the path to created directory.

For example, if you create "name" directory in a folder which contains "name.js", 'change' event for "name.js" will be fired.

https://gist.github.com/arubtsov/7c42600ab9f2c69791c400a130404b26

**Comment by UltCombo** [comment] 2016-06-20 11:16
The same problem has been reported here: floatdrop/gulp-watch#236

I can also reproduce the issue in Windows 10:

![Chokidar bug](https://cloud.githubusercontent.com/assets/2090712/16192356/33c4d50e-36bf-11e6-9bff-853b7ff87a77.gif)

```js
require('chokidar').watch('.', { ignoreInitial: true }).on('all', (event, path) => {
  console.log(event, path);
});
```

**Comment by es128** [comment] 2016-06-20 13:09
These events are being reported by node core `fs.watch` (you can see by listening to the `raw` event). Not sure what workarounds might be possible, it's difficult to doubt/verify `change` events coming from the underlying watch methods.

Using `usePolling: true` may be one workaround, although not recommended for many cases because it has other drawbacks.

**Comment by UltCombo** [comment] 2016-06-20 14:20
So, it is actually a bug in the Node core then? Do we already have a bug reported there?

**Comment by es128** [comment] 2016-06-20 18:46
I don't know whether there's currently an open issue about this behavior, and I am also unsure whether the issue can be fixed in node, or whether it's actually deeper down in the `ReadDirectoryChangesW` windows api.

The starting point would be to modify the repro script to show it happening with just `fs.watch` directly. I don't have a windows environment to work/test with currently.

**Comment by UltCombo** [comment] 2016-06-21 03:14
Looks like this is a known issue in libuv.
https://github.com/nodejs/node-v0.x-archive/issues/25689
https://github.com/paulmillr/chokidar/issues/420
https://github.com/nodejs/node/issues/4351
I believe all these issues should be fixed by https://github.com/libuv/libuv/pull/682

**Comment by es128** [comment] 2016-06-21 16:05
Ah, right ok so this is the same as #420. Will close this one as a dupe then and keep tracking it there. Unfortunately it still seems there is no solution that can be accomplished within chokidar.

**Closed by es128** 2016-06-21 16:05 UTC
