### ISSUE TITLE
Watching directory on shared folder events(add, change, ready) not triggered

### ISSUE THREAD

**Issue by dubeymahi48** [paulmillr/chokidar#1081] opened 2021-03-12 12:41 UTC
I am using Chokidar package to watch folders from shared directive having issue but working on local folder. Please help me I am using Windows-10 using below code

The issue is event not triggered if any new files added, updated and deleted.  I am using version - 3.5.1 

Thanks in advanced 
``` 
const resultFolder = `\\\\${IP}\\results`
chokidar.watch(resultFolder, {
                ignored: /(^|[\/\\])\../, // ignore dotfiles
                persistent: true,
		depth: 0,
                ignoreInitial: false,
		ignorePermissionErrors: true,
		awaitWriteFinish: true,
		usePolling: true
            })
          .on('add', path => log(`File ${path} has been added`))
          .on('change', path => log(`File ${path} has been changed`))
          .on('unlink', path => log(`File ${path} has been removed`));
            
            ```

**Comment by paulmillr** [comment] 2021-03-12 15:44
duplicate of existing issues

**Closed by paulmillr** 2021-03-12 15:44 UTC
