### ISSUE TITLE
windows unlink empty folder Trigger an error

### ISSUE THREAD

**Issue by Luncher** [paulmillr/chokidar#480] opened 2016-05-05 08:07 UTC
Uncaught Exception:
Error: watch null EPERM

  at exports.__errnoException (util.js:856:11)
  at FSEvent.FSWatcher._handle.onchange (fs.js:1306:21)

**Comment by es128** [comment] 2016-05-17 14:23
Need more details than this about what you were doing when this happened and how to reproduce. Possibly caused by you not adding a listener to the `error` event on your chokidar instance. Closing for now, but will reopen if you add details that indicate a bug in chokidar.

**Closed by es128** 2016-05-17 14:23 UTC

**Comment by kafoso** [comment] 2016-06-10 07:25
The `all` event won't catch this, but the `error` event willl.

    chokidar.on('error', function(error){
        console.error(error);
    });
