### ISSUE TITLE
Weird "change" event firing in parent directory of renamed file

### ISSUE THREAD

**Issue by RenaudParis** [paulmillr/chokidar#296] opened 2015-06-03 03:05 UTC
I am using Windows 7 64b.

Let's say I am watching the "dir1" directory. Inside, I have "dir2", "file1.txt". Inside "dir2" I have "file2.txt".

Whenever I rename "file2.txt" (is it possible to get a "renamed" event btw?), I get a "change" event on "file1.txt", don't know why.

**Here is my test log (I am recursively watching the "./data" directory):**
[Chokidar] add data\Nouveau document texte.txt *// created a file*
[Chokidar] add data\test2.txt *// renamed*
[Chokidar] unlink data\Nouveau document texte.txt *// renamed to test2.txt, actually*
[Chokidar] change data\blablabla.txt *// weird event*
[Chokidar] add data\bla\toto222.txt *// renamed*
[Chokidar] unlink data\bla\toto.txt *// renamed to toto222.txt, actually*
[Chokidar] change data\blablabla.txt *// weird event*
[Chokidar] add data\bla\tutu123.txt *// renamed*
[Chokidar] unlink data\bla\tutu.txt *// renamed to tutu123.txt, actually*
[Chokidar] change data\bla\toto222.txt *// again another weird event*
[Chokidar] add data\bla\toto\Nouveau document texte.txt *// created a file*
[Chokidar] change data\bla\toto222.txt *// again another weird event*
[Chokidar] add data\bla\toto\test3.txt *// renamed*
[Chokidar] unlink data\bla\toto\Nouveau document texte.txt *// renamed to test3.txt, actually*

**Comment by senritsu** [comment] 2015-07-15 07:01
Can confirm this issue and expand on the conditions under which it appears.

Given a folder structure of **what/ever/else/Foo/Bar/**

**Condition 1**: Anything inside subfolder (**Bar**) is changed, no matter if it is a file change, a new folder is added, a file or folder is deleted, etc.

**Condition 2**: There exists a file in the parent folder (**Foo**) whose name starts with the name of the subfolder (for example **Foo/Barbarian.js** or **Foo/BarberQuartet.js**)

**Effect**: Whenever chokidar encounters condition 1, it also fires a change event for all items matching condition 2.

**Comment by es128** [comment] 2015-07-15 13:16
Can you please provide the output from listening to the `raw` event?

**Comment by senritsu** [comment] 2015-07-15 16:13
with a file structure of 

```
Scripts/Page/globalization.coffee
Scripts/page.js
```

The watcher used for the output:

```
watcher = chokidar.watch globs.js
watcher.on 'raw', (event, file, details) ->
    console.log '> raw event output start'
    console.log '> event:'
    console.log event
    console.log '> file:'
    console.log file
    console.log '> details:'
    console.log details
    console.log '> raw event output start'
```
A save of *page.js* in visual studio results in the following output from a raw event listener:

```
> raw event output start
> event:
rename
> file:
12xbhxcl.2qa~
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
change
> file:
12xbhxcl.2qa~
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
change
> file:
12xbhxcl.2qa~
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
change
> file:
12xbhxcl.2qa~
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
rename
> file:
page.js~RF581e133.TMP
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
rename
> file:
null
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
change
> file:
page.js~RF581e133.TMP
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
rename
> file:
null
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
rename
> file:
page.js
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
change
> file:
page.js
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
rename
> file:
page.js
> details:
{ watchedPath: 'Scripts\\page.js' }
> raw event output start
> raw event output start
> event:
rename
> file:
page.js
> details:
{ watchedPath: 'Scripts\\page.js' }
> raw event output start
> raw event output start
> event:
change
> file:
page.js
> details:
{ watchedPath: 'Scripts\\page.js' }
> raw event output start
> raw event output start
> event:
rename
> file:
null
> details:
{ watchedPath: 'Scripts' }
> raw event output start
```

A save of *Page/globalization.coffee* results in the following output:
```
> raw event output start
> event:
rename
> file:
fyldge35.kpd~
> details:
{ watchedPath: 'Scripts\\Page' }
> raw event output start
> raw event output start
> event:
change
> file:
Page
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
change
> file:
page.js
> details:
{ watchedPath: 'Scripts\\page.js' }
> raw event output start
> raw event output start
> event:
change
> file:
fyldge35.kpd~
> details:
{ watchedPath: 'Scripts\\Page' }
> raw event output start
> raw event output start
> event:
change
> file:
fyldge35.kpd~
> details:
{ watchedPath: 'Scripts\\Page' }
> raw event output start
> raw event output start
> event:
rename
> file:
globalization.coffee~RF583830b.TMP
> details:
{ watchedPath: 'Scripts\\Page' }
> raw event output start
> raw event output start
> event:
rename
> file:
null
> details:
{ watchedPath: 'Scripts\\Page' }
> raw event output start
> raw event output start
> event:
change
> file:
globalization.coffee~RF583830b.TMP
> details:
{ watchedPath: 'Scripts\\Page' }
> raw event output start
> raw event output start
> event:
rename
> file:
null
> details:
{ watchedPath: 'Scripts\\Page' }
> raw event output start
> raw event output start
> event:
rename
> file:
globalization.coffee
> details:
{ watchedPath: 'Scripts\\Page' }
> raw event output start
> raw event output start
> event:
change
> file:
globalization.coffee
> details:
{ watchedPath: 'Scripts\\Page' }
> raw event output start
> raw event output start
> event:
rename
> file:
null
> details:
{ watchedPath: 'Scripts\\Page' }
> raw event output start
> raw event output start
> event:
change
> file:
Page
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
change
> file:
Page
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
change
> file:
page.js
> details:
{ watchedPath: 'Scripts\\page.js' }
> raw event output start
> raw event output start
> event:
change
> file:
page.js
> details:
{ watchedPath: 'Scripts\\page.js' }
> raw event output start
> raw event output start
> event:
change
> file:
Page
> details:
{ watchedPath: 'Scripts' }
> raw event output start
> raw event output start
> event:
change
> file:
page.js
> details:
{ watchedPath: 'Scripts\\page.js' }
> raw event output start
```

**Comment by es128** [comment] 2015-07-15 17:01
As you can see, the file system is emitting `change` events for `Scripts\page.js` even though you did not (deliberately) touch it. It seems there is an issue somewhere deeper than chokidar, and unless someone else has any ideas, I don't see how chokidar could effectively second-guess the system-level events in order to make adjustments that fix this problem.

**Comment by senritsu** [comment] 2015-07-15 20:27
Any ideas where the issue could come from? I am asking from a background of not knowing much about the internals of chokidar, how much of node's fs module it uses, etc.

Would it be possible the bug is on nodes side? Or does it seem more likely it is farther on the OS side of things?

**Comment by es128** [comment] 2015-07-15 20:32
For windows chokidar relies on node's `fs.watch` and just does things to try to smooth out its rough edges (the `raw` output is what `fs.watch` is reporting). 

The bug could be either in node or lower down in the system API it uses, but it would be worth reporting to node if it could be demonstrated with a simple script that only uses `fs.watch()` (i.e. cut out chokidar to show output similar to the above from the `raw` event output).

**Comment by es128** [comment] 2015-07-15 20:32
See if setting `usePolling: true` makes it any better.

**Comment by senritsu** [comment] 2015-07-16 08:12
I did a small synthetic test, and could reproduce the issue, both for chokidar and for fs.watch

Anytime a new file was added or removed from the folder *Foo*, a change event for the file *foobar.js* was sent as well. Some times (not everytime though) the same behaviour happened for changes to the file using notepad, which contrasts a bit to our problem in visual studio. In VS every change resulted in the buggy behaviour. This might be due to the mechanics VS employs while saving a file, maybe some temp file copying or similar.

```
var chokidar = require('chokidar');
var fs = require('fs');

function zerofill(i){
  return (i < 10 ? '0' : '') + i;
}

function timestamp() {
  var now = new Date();
  return '[' + zerofill(now.getHours()) + ':' + zerofill(now.getMinutes()) + ':' + zerofill(now.getSeconds()) + ']'
}

var watcher = chokidar.watch('./TestRoot/**/*');
watcher.on('change',function(file){console.log(timestamp() + ' chokidar           >>> ' + file);})

watcher = chokidar.watch('./TestRoot/**/*', {usePolling:true});
watcher.on('change',function(file){console.log(timestamp() + ' chokidar (polling) >>> ' + file);})

fs.watch('./TestRoot/', {recursive:true}, function(event, filename){
  if (event === 'change') {
    console.log(timestamp() + ' fs.watch (folder)  >>> ' + filename);
  }
});

fs.watch('./TestRoot/foobar.js', function(event, filename){
  if (event === 'change') {
    console.log(timestamp() + ' fs.watch (file)    >>> ' + filename);
  }
});
```

**Comment by es128** [comment] 2015-11-25 18:02
This phenomenon appears to be caused deeper at the system level. There's no bug in chokidar, nor anything that could be done at this level to correct it. Closing

**Closed by es128** 2015-11-25 18:02 UTC

**Comment by wc-matteo** [comment] 2016-05-03 21:16
Could it be related to [this](https://github.com/paulmillr/chokidar/issues/420)?
