### ISSUE TITLE
unwatch() and close() after a delay from watching does not allow process to exit in OSX 

### ISSUE THREAD

**Issue by Zugwalt** [paulmillr/chokidar#218] opened 2015-01-21 23:39 UTC
After a few milliseconds, unwatching and closing doesn't allow process to exit in OSX.

```javascript
var chokidar = require('chokidar');

console.log('watching',__dirname);
var watcher = chokidar.watch(__dirname);

setTimeout(function() {
    console.log('unwatching');
    watcher.unwatch(__dirname);
    console.log('closing');
    watcher.close();
}, 1000);
````

**Comment by es128** [comment] 2015-01-21 23:40
Dupe of https://github.com/pipobscure/fsevents/issues/50

**Comment by es128** [comment] 2015-01-27 17:38
Fixed in fsevents v0.3.5

**Closed by es128** 2015-01-27 17:38 UTC
