### ISSUE TITLE
no more watching after first change event

### ISSUE THREAD

**Issue by kapouer** [paulmillr/chokidar#278] opened 2015-04-10 08:27 UTC
Hi,
i'm watching a directory with {depth: 0} as the sole option,
and after first change on a file, it seems to be ignoring further changes.
Using chokidar 1.0.1.

**Comment by artem-malko** [comment] 2015-04-10 08:58
set `persistent ` option to true.

**Comment by kapouer** [comment] 2015-04-10 10:13
Shouldn't it be the default value ?

**Comment by kapouer** [comment] 2015-04-10 10:15
It doesn't solve the problem

**Comment by es128** [comment] 2015-04-10 11:17
OS? Other options? Text editor?

**Comment by kapouer** [comment] 2015-04-10 11:49
Umpgh yes sorry, more precisions:

platform debian/jessie, linux 3.16, gnome 3.14.

* i watch a directory with these options explicitely set:
```
watcher: chokidar.watch(dir, {depth: 0, persistent: true, atomic: true, followSymlinks: true})
.on('change', changeListener);
```
* when i change a normal file twice, everything's all right
* when i change twice the target of a symlink, the change event is fired twice (or sometimes more times in a row) if i change it twice using `vim`, but  as soon as i change it using `gedit` no more changes are detected.

Same kind of problem with atomic: false option, in which case i see change and unlink events on regular file, and only one change event on symlink.

**Comment by kapouer** [comment] 2015-04-10 11:50
change /xxx/public/js/.goutputstream-GIOPWX
unlink /xxx/public/js/.goutputstream-GIOPWX
change /xxx/public/js/bindings.js

**Comment by es128** [comment] 2015-04-10 11:53
This is the second or third report of `gedit` causing problems. I still haven't had a chance to study its raw event behavior to augment the `atomic` adjustments. 

In the meantime if you stick to `vim` or other editors you should be fine.

**Comment by es128** [comment] 2015-04-10 22:03
Closing as dupe of #237

**Closed by es128** 2015-04-10 22:03 UTC
