### ISSUE TITLE
Chokidar (fs.watch?) seems to lock parent of the watched

### ISSUE THREAD

**Issue by CxRes** [paulmillr/chokidar#320] opened 2015-07-29 01:44 UTC
Chokidar seems to lock parent directory on Windows 7 when being watched? 

Is this expected? Is this an artifact of the iojs `fs.watch()` method? Are there any possible work arounds?

**Comment by es128** [comment] 2015-07-29 13:55
> Is this an artifact of the iojs `fs.watch()` method?

Yes

> Is this expected?

I've heard it reported before; it certainly isn't deliberate

> Are there any possible work arounds?

`usePolling: true` perhaps

**Comment by es128** [comment] 2015-07-29 14:04
https://github.com/joyent/node/issues/8371
https://github.com/joyent/node/issues/3963

Closing this issue as there does not appear to be anything chokidar could do to have an impact on this. Plus it appears to be the intended behavior of the windows file system.

**Closed by es128** 2015-07-29 14:04 UTC

**Comment by Elephant-Vessel** [comment] 2016-03-05 17:32
Hey, it seems they have fixed this recently: https://github.com/nodejs/node/issues/375, https://github.com/nodejs/node/blob/master/deps/uv/ChangeLog#L277, https://github.com/nodejs/node/commit/a338eb3c3e712fcaacdb475cc6f3378259a3d534
