### ISSUE TITLE
watcher.add for Program Files (x86) does not work on Windows

### ISSUE THREAD

**Issue by kunalshetye** [paulmillr/chokidar#411] opened 2015-12-07 12:32 UTC
I've recently started using chokidar and I can't seem to get the 'add' event fired when trying to monitor "D:\Program Files (x86)" on Windows.

I can access the folder and get list of files via regular **fs** commands.

But when trying to use chokidar I end up with no events being fired at all, it's as if the directory was never added!

Has anyone encountered this before?

Regards,
Kunal

**Comment by es128** [comment] 2015-12-07 14:11
Looks like a dupe of #300, which is the next issue I was looking to tackle.

**Closed by es128** 2015-12-07 14:11 UTC
