### ISSUE TITLE
Following symlinks does not work when matched against `sth*` pattern

### ISSUE THREAD

**Issue by Reinmar** [paulmillr/chokidar#419] opened 2015-12-17 16:26 UTC
I've got the following setup:

In `/www/ckeditor5/node_modules/` I've got two symlinks:

```
lrwxr-xr-x    1 p  staff     29 15 Dec 17:14 ckeditor5-foo -> /www/ckeditor5-foo
lrwxr-xr-x    1 p  staff     39 15 Dec 17:16 ckeditor5-bar -> /www/ckeditor5-bar
```

When using chokidar as follows, changes made in `ckeditor5-core` are not discovered. However, the changes made in `ckeditor5-bar` are.

```
const chokidar = require( 'chokidar' );

chokidar.watch(
    [
        '/www/ckeditor5/node_modules/ckeditor5-f*/**/*.js',
        '/www/ckeditor5/node_modules/ckeditor5-bar/**/*.js',
    ],
    {
        ignoreInitial: true
    }
).on( 'all', ( event, path ) => {
    console.log( event, path );
} );
```

When I change the first pattern to `'/www/ckeditor5/node_modules/ckeditor5-foo/**/*.js'` everything works fine.

I'm on MacOS 10.11.2, Node v5.2.0.

**Comment by es128** [comment] 2015-12-17 16:38
A version of this issue was fixed with https://github.com/paulmillr/chokidar/pull/406, but that wasn't with the glob pattern on the symlink's path itself.

**Comment by jfbibeau** [comment] 2016-02-10 22:03
I believe I'm also run into this issue. I'm watching a path that has a glob pattern in it containing a symlink (via browsersync), and chokidar is not watching files under a symlink. 

Any idea if there's a workaround I could use?

**Comment by jfbibeau** [comment] 2016-02-10 22:44
Found a workaround by watching the parent then using ignored to filter the files, but my directory was gigantic and "ignored" doesn't seem to be as efficient as matching with glob pattern itself (my cpu almost melted).

Found a second workaround by iterating through my directory and adding individual watches against each folder in the parent folder, and glob after that. That seems to work fine without any performance penalty. Hope this helps someone!

Still would be nice to have this working :) Cheers.

**Comment by trainerbill** [comment] 2016-04-26 16:17
+1. My issue is a little different.  It doesn't work when watching a folder with symlinks.  I have a modules/ folder with symlinks in it and watching ./modules/*/.js. Using Gulp 4 with latest chokidar. It does not work with matching a pattern in folder/symlink/pattern. If I watch the direct file path without a pattern it works with symlink and if I remove the symlink and copy the directory in /modules folder it works.  So the issue is watching a folder with symlinks as subdirectories.

**Comment by ThomasBrierley** [comment] 2016-04-28 10:15
+1. I'm experiencing this in the same way @trainerbill is: where the symlink is a subdirectory matched by the glob, the watch does not recurse through that symlink regardless of glob.

In-case it's of any use, I had a similar problem with vinyl-fs not srcing files when symlinked subdirectories are present and matching with something like ```foo/**/*.*``` (where foo is not a symlink), purely by instinct I found that ```foo/**/**/*.*``` will inspect symlinked subdirectories under foo and deeper. However this does not work with chokidar.

**Comment by ThomasBrierley** [comment] 2016-05-09 13:49
One workaround if you don't mind it watching an entire directory without filtering: Specify only the top level directory without any globbing... symlinked subdirectories are recursed normally.

**Comment by lkraav** [comment] 2017-12-06 10:37
As far as I can tell on Linux, this is still a problem today.

**Closed** 2018-09-06 09:28 UTC
Labels: bug, unpopular
