### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by CxRes** [paulmillr/chokidar#736] opened 2018-06-16 08:45 UTC
I just cloned the repo and ran tests
```
npm run tests
```

This is what i get: 
```
> chokidar@2.0.3 test D:\Users\Rahul\dev\chokidar
> nyc mocha --exit



  1) "before all" hook

  0 passing (2s)
  1 failing

  1) "before all" hook:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.




----------------------|----------|----------|----------|----------|-------------------|
File                  |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------------|----------|----------|----------|----------|-------------------|
All files             |     8.37 |      0.5 |     2.38 |     9.29 |                   |
 chokidar             |    10.05 |     0.33 |     3.23 |    11.56 |                   |
  index.js            |    10.05 |     0.33 |     3.23 |    11.56 |... 17,718,720,742 |
 chokidar/lib         |     6.65 |     0.68 |     1.56 |     7.06 |                   |
  fsevents-handler.js |     7.95 |      1.3 |     3.13 |     8.23 |... 92,395,397,399 |
  nodefs-handler.js   |     5.58 |        0 |        0 |     6.12 |... 77,480,483,484 |
----------------------|----------|----------|----------|----------|-------------------|
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chokidar@2.0.3 test: `nyc mocha --exit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chokidar@2.0.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

on:
Windows 10 x64
Node 8.11.2
Chokidar 2.0.3

**Comment by paulmillr** [comment] 2018-09-06 09:35
Duplicate of #712

**Closed by paulmillr** 2018-09-06 09:35 UTC
