### ISSUE TITLE
chokidar adds executable files that don't match glob

### ISSUE THREAD

**Issue by jedwards1211** [paulmillr/chokidar#558] opened 2016-11-27 20:20 UTC
chokidar 1.6.1
node 5.12.0

When I run
```js
  chokidar.watch('./**/*.record.js', {
    awaitWriteFinish: true,
  }).on('all', (event: Object, path: string) => {
    console.log(event, path)
  })
```
It prints the following.  It seems like all files with an executable flag are mistakenly getting added?
```
add test.record.js
add node_modules/.bin/flow
add node_modules/.bin/latest-version
add node_modules/.bin/loose-envify
add node_modules/.bin/rc
add node_modules/.bin/rimraf
add node_modules/.bin/strip-json-comments
add node_modules/.bin/user-home
add .git/hooks/pre-commit
add node_modules/.bin/_mocha
add node_modules/.bin/acorn
add node_modules/.bin/babel
add node_modules/.bin/babel-doctor
add node_modules/.bin/babel-external-helpers
add node_modules/.bin/babel-node
add node_modules/.bin/babylon
add node_modules/.bin/coveralls
add node_modules/.bin/escodegen
add node_modules/.bin/esgenerate
add node_modules/.bin/eslint
add node_modules/.bin/esparse
add node_modules/.bin/esvalidate
add node_modules/.bin/esw
add node_modules/.bin/flow-watch
add node_modules/.bin/handlebars
add node_modules/.bin/har-validator
add node_modules/.bin/istanbul
add node_modules/.bin/js-yaml
add node_modules/.bin/jsesc
add node_modules/.bin/json5
add node_modules/.bin/mkdirp
add node_modules/.bin/mocha
add node_modules/.bin/nodemon
add node_modules/.bin/nopt
add node_modules/.bin/nyc
add node_modules/.bin/regjsparser
add node_modules/.bin/semver
add node_modules/.bin/shjs
add node_modules/.bin/sshpk-conv
add node_modules/.bin/sshpk-sign
add node_modules/.bin/sshpk-verify
add node_modules/.bin/touch
add node_modules/.bin/uglifyjs
add node_modules/.bin/uuid
add node_modules/.bin/which
add node_modules/fsevents/node_modules/.bin/rc
add node_modules/fsevents/node_modules/.bin/rimraf
add node_modules/fsevents/node_modules/.bin/strip-json-comments
add node_modules/nyc/node_modules/.bin/loose-envify
add node_modules/nyc/node_modules/.bin/rimraf
add node_modules/update-notifier/node_modules/.bin/repeating
add node_modules/acorn-jsx/node_modules/.bin/acorn
add node_modules/fsevents/node_modules/.bin/har-validator
add node_modules/fsevents/node_modules/.bin/mkdirp
add node_modules/fsevents/node_modules/.bin/node-pre-gyp
add node_modules/fsevents/node_modules/.bin/nopt
add node_modules/fsevents/node_modules/.bin/semver
add node_modules/fsevents/node_modules/.bin/sshpk-conv
add node_modules/fsevents/node_modules/.bin/sshpk-sign
add node_modules/fsevents/node_modules/.bin/sshpk-verify
add node_modules/fsevents/node_modules/.bin/uuid
add node_modules/istanbul/node_modules/.bin/nopt
add node_modules/nyc/node_modules/.bin/babylon
add node_modules/nyc/node_modules/.bin/handlebars
add node_modules/nyc/node_modules/.bin/jsesc
add node_modules/nyc/node_modules/.bin/mkdirp
add node_modules/nyc/node_modules/.bin/semver
add node_modules/nyc/node_modules/.bin/uglifyjs
add node_modules/nyc/node_modules/.bin/which
add node_modules/regjsparser/node_modules/.bin/jsesc
add node_modules/nyc/node_modules/yargs/node_modules/.bin/window-size
```

**Comment by es128** [comment] 2016-11-28 15:38
Dupe of #544

**Closed by es128** 2016-11-28 15:38 UTC
