### ISSUE TITLE
chokidar Ignoring files, when the filename contains [chars] or (chars)

### ISSUE THREAD

**Issue by bunterWolf** [paulmillr/chokidar#456] opened 2016-04-01 18:05 UTC
Hey :)

(char) and [char] in a Filename is a problem for chokidar, if it is the path for watch()
If a file [something].txt is the child of a watched folder, everything works fine.

chokidar 1.4.3
OS X 10.11

**Short:**
```
let watcher1 = chokidar.watch(  '/.../buggy_[x].txt'  )
watcher1.on('ready', () => {
  console.log(watcher1.getWatched())
})
console: {}
```

**Example to follow:** [chokTest.zip](https://github.com/paulmillr/chokidar/files/200099/chokTest.zip)

Thanks!

**Comment by ishmayeck** [comment] 2016-04-20 20:18
I'm seeing the same thing on Windows 10, trying to watch the "Dropbox (Personal)" directory created by Dropbox. It seems parentheses or brackets anywhere in the bath will break it.

It's worth noting that fs.watch() sees the changes.

I will continue digging, and report back if I stumble upon anything useful.

**Comment by es128** [comment] 2016-04-20 22:02
Closing as duplicate of #300

**Closed by es128** 2016-04-20 22:02 UTC
