### ISSUE TITLE
Watchify runs twice and refuses to respond to additional file changes

### ISSUE THREAD

**Issue by vz8** [paulmillr/chokidar#395] opened 2015-11-08 21:57 UTC
Hi, just asked about this over in watchify, and they suggested it was a chokidar issue:

I'm running a gulp task which fails after two changes to a js file (any changes, however slight)

My config:

ubuntu 14.04.3 (run with a fresh native install as well as on virtualbox 5.0.5)
node@0.12.7 && 5.0.0
npm@3.3.6
watchify@3.3.0 && 3.4.0
browserify@11.2.0 && 12.0.1
chokidar@1.1.0 && 1.2.0

Both a fresh native install of Ubuntu 14.04.3 and a VirtualBox guest on a Windows 8.1 workstation exhibited the same behavior: run gulp with watchify, the task notices 2 changes to a js file, then stops responding completely. Enabling polling doesn't help in my case.

Watchify behaves correctly on OSX with the exact same gulpfile, scripts, and user preferences.

Thanks for any advice/feedback.

**Comment by es128** [comment] 2015-11-09 02:57
Sounds like it might be text editor related. Try using different editors or using `touch` to see if that has any impact. 

If not, please add event listeners that log out what's being emitted under the `all` and `raw` events so we can see what that reveals.

**Comment by vz8** [comment] 2015-11-09 05:00
I've used vim and nano, same results. I've tried touching the file, and cat textfile >> watchedfile.js  as well with no effect.

Will try adding some listeners and more logging next, thanks.

**Comment by es128** [comment] 2015-11-23 17:54
Not enough information here to investigate with. Closing for now, but will reopen if more evidence of the problem being caused by an issue in chokidar can be provided.

**Closed by es128** 2015-11-23 17:54 UTC
