### ISSUE TITLE
Change event fires twice for the same file with a different path

### ISSUE THREAD

**Issue by jameslnewell** [paulmillr/chokidar#390] opened 2015-11-05 17:43 UTC
On `OSX@10.11.1`. Using `chokidar@1.0.0-1.2.0`.

```
change src/assets/index.scss <= relative path from cwd
change /Users/james/code/github/generator-fed/demo/src/assets/index.scss
```

---

I found the `cwd` option which makes the path relative and fixes the issue, however chokidar should probably only emit one event regardless of whether the `cwd` option is set or not?

**Comment by jameslnewell** [comment] 2015-11-05 17:51
It's easily fixed by adding the following line before line [216](https://github.com/jameslnewell/chokidar/blob/master/index.js#L214):

    path = sysPath.relative(this.options.cwd || process.cwd(), path);

However, then after some changes I get `src/assets/index.scss` and after other changes I get `/Users/james/code/github/generator-fed/demo/src/assets/index.scss` reported as the path.

**Comment by jameslnewell** [comment] 2015-11-05 17:55
And that can be worked around by always forcing the absolute path when the `cwd` option isn't specified... Replacing line [120](https://github.com/jameslnewell/chokidar/blob/master/index.js#L120) with:

    if (this.options.cwd) {
      path = sysPath.relative(this.options.cwd, path);
    } else {
      path = sysPath.resolve(process.cwd(), path);
    }

**Comment by es128** [comment] 2015-11-05 19:16
I can't reproduce this. Can you show the code you're using - in particular how you define the paths you are watching?

**Comment by jameslnewell** [comment] 2015-11-05 19:28
I'm using the `.unwatch()` and `.add()` methods [here](https://github.com/digitaledgeit/sass-composer/blob/master/lib/watcher.js#L77). In my simple example the param passed to `unwatch/add` is always `[ '/Users/james/Work/nib/generator-fed/demo/src/assets/index.scss' ]`.

Note: using the `cwd` option makes it work because it always uses the relative path.

**Comment by es128** [comment] 2015-11-05 19:36
Are you sure that it's also an absolute path when `chokidar.watch()` is instantiated?

The bug appears to be either that it emits events with a relative path even though an absolute path was provided (regardless of the duplication), or that it doesn't recognize the equivalency of a matching absolute and relative path that a user provided by accident and sets up redundant watching on it.

The former option is the one that's pretty well tested and I can't reproduce, so I suspect the latter is somehow occurring on your side.

**Comment by jameslnewell** [comment] 2015-11-05 19:43
Thats it, when initiated with a relative path it happens but not with an absolute path.

**Comment by es128** [comment] 2015-11-05 19:52
So this is a pretty minor edge case, but it's worth investigating and addressing if the fix doesn't involve significant tradeoffs.

Should be pretty easy to write a test now that the use case is well understood.

**Comment by jameslnewell** [comment] 2015-11-05 20:02
var path = require('path');
    var chokidar = require('chokidar');
    
    var file = './css/index.scss';
    var watcher = chokidar.watch(file, {});
    
    function bundle() {
      setTimeout(function() {
        watcher.unwatch([path.resolve('.', file)]);
        watcher.add([path.resolve('.', file)]);
      }, 0)
    }
    
    watcher.on('change', function(file) {
      console.log('change', file);
      bundle();
    });
    
    bundle();

Prints:

    change css/index.scss
    change /Users/james/tmp/chokidar-example/css/index.scss

**Comment by es128** [comment] 2015-11-05 20:04
Right, you started watching the file as a relative path, then added it again as an absolute path. Chokidar is failing to recognize that the two paths point to the same file.

I call it a minor edge case because mixing relative/absolute references to the same path like this is not something I've seen users do before.

**Comment by jameslnewell** [comment] 2015-11-05 20:16
Yeah `node-sass` gives me an array of all the `@import`ed files as absolute paths but the input path can be in whatever format the user provides - rel or abs. I was just passing these straight to `chokidar` assuming it would handle it.

**Comment by es128** [comment] 2015-11-05 20:18
Understood. Like I said, I agree that it ought to be fixed in chokidar so that it does just handle this sort of scenario seamlessly.

**Comment by jameslnewell** [comment] 2015-11-05 20:20
Cool! :sunglasses:

**Closed** 2018-09-06 09:26 UTC
Labels: bug, unpopular
