### ISSUE TITLE
chokidar slows down every time watched files are changed

### ISSUE THREAD

**Issue by dragonflypl** [paulmillr/chokidar#405] opened 2015-12-02 09:51 UTC
I have build setup using gulp and I use chokidar for listening for file changes:

``` javascript
var buildWatcher = chokidar.watch(paths, { ignoreInitial: true });

buildWatcher
    .on('add', function(filePath) {
        gulpUtil.log("File event: " + gulpUtil.colors.cyan(path.basename(filePath) + ' add'));
        gulp.start(key + suffix);
    })
    .on('change', function(filePath) {
        gulpUtil.log("File event: " + gulpUtil.colors.cyan(path.basename(filePath) + ' change'));
        gulp.start(key + suffix);
    })
    .on('unlink', function(filePath) {
        gulpUtil.log("File event: " + gulpUtil.colors.cyan(path.basename(filePath) + ' unlink'));
        gulp.start(key + suffix);
    });
```

I'm struggling with an issue, like a memory leak or sth, namely: every time a file is saved, the watch process is taking more resources (CPU in Task Manager) and as a result whole gulp.start'ed task takes longer. When starting new gulp, initially tasks are running smoothly, CPU usage is low, started tasks take a couple of ms to execute. But saving (even the same file) a few times, and CPU usage raises to 100% for a few seconds.

I tried switching to gulp.watch (3.9):

``` javascript
gulp.watch(paths, function(event) {
    gulpUtil.log("File event: " + gulpUtil.colors.cyan(path.basename(event.path) + ' ' + event.type));
    gulp.start(key + suffix);
}).on('error', function(error) {
    gulpUtil.log(error);
});
```

and here I don't have this issue. However gulp.watch does not support listening for new files, and this is why I wan't to use chokidar.

Do you know what could be the issue behind chokidar performance issue? How can it be diagnosed?

Thanks

**Comment by es128** [comment] 2015-12-02 18:00
Closing as dupe of #328. If you have anything else to report, please continue the discussion there.

In the meantime:

a) Try `gulp.watch` with gulp v4, which uses chokidar
b) You may be satisfied with the `usePolling: true` option

**Closed by es128** 2015-12-02 18:00 UTC
