### ISSUE TITLE
Watch does not work for glob pattern '<dir>/**' if '<dir>' does not exist on fs

### ISSUE THREAD

**Issue by eGavr** [paulmillr/chokidar#745] opened 2018-07-14 14:16 UTC
**Describe the bug**

Files are not being watched for glob `<dir>/**` if `<dir>` does not exist.

**Versions (please complete the following information):**
 - Chokidar version [2.0.4]
 - Node version [8.6.0]
 - OS version: [Ubuntu 16.04]

**To Reproduce**

```js
// index.js
const chokidar = require('chokidar');
const watcher = chokidar.watch(['dir/**']);

watcher.on('add', path => console.log(path));
```

Run this code and create `file.ext` in `dir`:

```bash
mkdir dir && touch dir/file.ext
```

You will see nothing in console.

**Comment by paulmillr** [comment] 2019-09-30 23:29
Duplicate of latter-created #872

**Closed by paulmillr** 2019-09-30 23:29 UTC
Labels: linux
