### ISSUE TITLE
Glob failing to filter out symlinks that do not match the pattern in 1.6.1

### ISSUE THREAD

**Issue by seflless** [paulmillr/chokidar#544] opened 2016-10-23 11:30 UTC
What am I doing wrong here. I keep getting a 'add' event for every single file in a path I'm doing a watch on with a glob pattern.

```
var glob = path.resolve(watchDirectory) + "/**/*.dot";
console.log("Glob pattern: \n"+glob);
chokidar.watch(glob, {ignoreInitial: false}).on('all', (event, path) => {
    console.log(event, path);
});
```

This outputs: (Notice the files being with 'add' events that don't have .dot extensions as per the glob pattern.

```
Glob pattern:

/Users/francoislaberge/dev/diagrams/**/*.dot
add /Users/francoislaberge/dev/diagrams/simple.dot
add /Users/francoislaberge/dev/diagrams/node_modules/.bin/electron
add /Users/francoislaberge/dev/diagrams/node_modules/electron-prebuilt/node_modules/.bin/extract-zip
add /Users/francoislaberge/dev/diagrams/node_modules/electron-prebuilt/node_modules/.bin/electron-download
add /Users/francoislaberge/dev/diagrams/node_modules/fsevents/node_modules/.bin/rc
add /Users/francoislaberge/dev/diagrams/node_modules/fsevents/node_modules/.bin/rimraf
add /Users/francoislaberge/dev/diagrams/node_modules/fsevents/node_modules/.bin/strip-json-comments
add /Users/francoislaberge/dev/diagrams/node_modules/fsevents/node_modules/.bin/har-validator
add /Users/francoislaberge/dev/diagrams/node_modules/fsevents/node_modules/.bin/mkdirp
add /Users/francoislaberge/dev/diagrams/node_modules/fsevents/node_modules/.bin/node-pre-gyp
add /Users/francoislaberge/dev/diagrams/node_modules/fsevents/node_modules/.bin/nopt
add /Users/francoislaberge/dev/diagrams/node_modules/fsevents/node_modules/.bin/semver
add /Users/francoislaberge/dev/diagrams/node_modules/fsevents/node_modules/.bin/sshpk-sign
add /Users/francoislaberge/dev/diagrams/node_modules/fsevents/node_modules/.bin/sshpk-conv
add /Users/francoislaberge/dev/diagrams/node_modules/fsevents/node_modules/.bin/sshpk-verify
add /Users/francoislaberge/dev/diagrams/node_modules/fsevents/node_modules/.bin/uuid
...
```

**Comment by 00dani** [comment] 2016-11-21 00:23
I'm experiencing exactly the same issue - I have Node v7.1.0 and chokidar 1.6.1 on MacOS Sierra. It looks like Chokidar already has known issues with Node 7 (see #550).

**Comment by jedwards1211** [comment] 2016-11-28 18:48
I'm seeing this with Node v5.12.0 and chokidar 1.6.1 on OS X El Capitan.

**Comment by jedwards1211** [comment] 2016-11-28 18:49
@francoislaberge is simple.dot marked executable?  I think for some reason it's matching executable files, rather than *everything*.

**Comment by jedwards1211** [comment] 2016-11-28 18:50
@francoislaberge it doesn't look like it's matching *everything* -- just files that actually match your glob pattern and files marked executable.  You should change the title to "chokidar adds executable files that don't match glob"

**Comment by francoislaberge** [comment] 2016-11-28 20:45
I'm not sure if that's the case or if it was just picking up my binaries first before I cut off my copy/paste of the print out. 

I no longer have this code setup anymore as I moved onto using another approach to work around it, otherwise I would verify if your theory is true. It certainly looks true from my report.

**Comment by birjolaxew** [comment] 2016-11-28 23:15
Should be mentioned that the executables are actually symlinks, and are handled by [`wh.filterDir`](https://github.com/paulmillr/chokidar/blob/master/index.js#L429-L439), not [`wh.filterPath`](https://github.com/paulmillr/chokidar/blob/master/index.js#L410-L417). They pass this, when they shouldn't. Unfortunately I have run out of time for debugging right now, but hopefully someone else can debug much quicker now that it's isolated.

**Comment by es128** [comment] 2016-11-29 03:09
So was this issue introduced in chokidar 1.6.1? Can you check whether reverting down to 1.6.0 resolves it?

The symlinks going to `filterDir` instead of `filterPath` came from https://github.com/paulmillr/chokidar/issues/530, but that solution may not have been vetted enough before going out.

Your last point about there being better ways to handle `filterDir` - sure, probably. The intention of that function is to tell readdirp whether to recurse into a directory or not, so it's intended to only rule things out very conservatively because the worst case is drilling down into dirs where none of the entries end up matching. You can see there's a globstar (`**`) short-circuit in there for situations like the one you described. But if you identify a better way, PR welcome.

**Comment by birjolaxew** [comment] 2016-11-29 15:49
Yes, reverting to 1.6.0 does resolve the issue.

I believe the proper way to fix this would be to check if the realpath that the symlink points to is a directory/file, and then use the appropriate filtering method rather than simply defaulting to dir filtering when a symlink is encountered.

**Comment by es128** [comment] 2016-11-29 15:51
Yes, but it's going to be a bit messy to work some new async-ness into there

**Comment by birjolaxew** [comment] 2016-11-29 18:16
Given that the filtering functions are used by `readdirp`, I don't think async is even supported. It'd have to use the sync variants either way, which greatly simplifies the implementation.

**Comment by es128** [comment] 2016-11-29 18:20
Avoiding any sync fs operations has been a cardinal rule here, but if there's no choice, then I guess that'll just be the penalty that has to be paid for symlinks.

But perhaps these should just not be filtered at the readdirp level and get handled elsewhere.

**Comment by jedwards1211** [comment] 2016-11-29 21:29
@birjolaxew wait, so if there's a directory symlink e.g. `builds/latest -> builds/0.9.20`, would files inside it match `builds/latest/*`, `builds/0.9.20/*`, or both?  I would think all paths scanned should be tested against the glob(s) without resolving symlinks.

**Comment by birjolaxew** [comment] 2016-11-29 23:12
@jedwards1211 A symlink is essentially the same thing as having a file in two places. If you have a directory `latest` which is a symlink to `0.9.20`, then any files inside `0.9.20` also exist inside `latest`. If you watch both folders, you'll get two `"changed"` events every time a file inside `0.9.20` changes - because it's essentially two files being changed. If you only watch one, you'll only get the `"changed"` event related to that folder.

The issue here is that symlinks can also be files, while chokidar assumes that all symlinks are folders. This means file symlinks (like those in `node_modules/.bin/`) are filtered based on directory rules, not file rules.

**Comment by jedwards1211** [comment] 2016-12-01 18:44
@birjolaxew yes I understand how symlinks work.  I just wanted to make sure that it wasn't filtering on paths with all symlinks filtered out, because that would be a major problem.

Ideally chokidar should handle symlinks in exactly the same way as multiple hardlinks to the same file/directory, right?

**Comment by birjolaxew** [comment] 2016-12-01 19:14
@jedwards1211 Yes. Chokidar will handle symlink as if though they were folders/files - except for the issue described here.

**Comment by TehShrike** [comment] 2017-03-14 18:53
I just ran into this as well.  I suggest 1.6.1 be reverted for now to fix the regression.  https://github.com/paulmillr/chokidar/commit/9eeecf605ba24798d90e93206d6867d8469320f7

**Comment by TimboKZ** [comment] 2019-08-10 22:47
The issue still exists on `v3.0.2`...

**Comment by zhylmzr** [comment] 2019-08-20 05:54
I just encountered this problem in `3.0.2`. My system environment is `macOS 10.14.5`, because I use gulp in the project, gulp depends on chokidar, I can only ignore all symlink files by `followSymlinks : false` now.

**Comment by paulmillr** [comment] 2019-08-20 08:44
If someone can make a reproducible repository with the issue, thay would help.

**Comment by birjolaxew** [comment] 2019-08-20 09:48
@paulmillr https://github.com/birjolaxew/chokidar-544

**Comment by jagthedrummer** [comment] 2023-06-06 20:17
Am also having problems with this in 3.5.3.

**Closed** 2024-07-01 20:22 UTC
Labels: mac, has test case
