### ISSUE TITLE
ready event sometimes delivered before other events, and sometimes multiple times

### ISSUE THREAD

**Issue by RoystonS** [paulmillr/chokidar#950] opened 2019-11-24 12:48 UTC
**Describe the bug**

**Versions (please complete the following information):**
 - Chokidar version 3.3.0 (and 3.1.0; behaviour noticed after upgrading from 2.1.8)
 - Node version 12.13.1
 - OS version: Windows 10 (but I also see the same behaviour on Ubuntu)

**To Reproduce:**

With a simple configuration, I'm able to get
* `ready` events delivered _before_ any other events (e.g. `add`s)
* multiple `ready` events

Here's a sample program:

```
const chokidar = require('chokidar');
const watcher = chokidar.watch(['file1', 'file2', 'file3'], {});
watcher
  .on('add', p => {
	console.log("Chokidar ADD", p);
})
  .on('ready', () => {
	console.log("Chokidar READY");
});
```

If this is run by itself with no matching files, the output is:

```
Chokidar READY
Chokidar READY
```
i.e. we get _two_ `ready` events.

If I create a `file3`, I get:
```
Chokidar READY
Chokidar ADD file3
Chokidar READY
```
If I create _instead_ file `file2`, I get:

```
Chokidar ADD file2
Chokidar READY
Chokidar READY
```
(The same pattern of output also occurs if I create only file `file1` instead.)

If both `file1` and `file2` exist, I get the correct output:

```
Chokidar ADD file1
Chokidar ADD file2
Chokidar READY
```

If I change the code to change all of the inputs to wildcards
```
const watcher = chokidar.watch(['file1*', 'file2*', 'file3*'], {});
```
the behaviour appears to be correct, with a single `ready` event, and the `add`s delivered beforehand.

Also, if I have a mixture of wildcards and non-wildcards, and any of the non-wildcard patterns fail to match, that appears to be the case that causes the issue.  Having a wildcard pattern that fails to match is fine.

**Expected behavior**

* No situation should ever caused more than one `ready event to be delivered
* The single `ready` event should always be delivered after any initial `add`s have been delivered.

**Additional context**

**Comment by paulmillr** [comment] 2019-11-24 14:44
You need to either watch an existing file, or a directory with proper filters. We don’t currently support watching non-existent root files.

**Comment by paulmillr** [comment] 2019-11-24 14:45
Duplicate of #872

**Closed by paulmillr** 2019-11-24 14:45 UTC

**Comment by RoystonS** [comment] 2019-11-24 14:56
Thanks. I hadn't spotted they were the same issue.

If #872 proves to be hard to fix, an error message saying that the API request is unsupported would help somewhat: it took me several hours to diagnose what had gone wrong after the upgrade from chokidar 2.1.8 to 3.3.0 caused our builds to behave weirdly.
