### ISSUE TITLE
change event fired with wrong files

### ISSUE THREAD

**Issue by valaxy** [paulmillr/chokidar#376] opened 2015-10-24 11:20 UTC
For example, I have three files: `test.js` and `test.jsx` and `test.jsxy`

```javascript
chokidar.watch(__dirname)
	.on('change', function (absoluteFilePath) {
		console.log('change', absoluteFilePath)
	})
```

When I changed `test.js` and `test.js` only, chokidar report all the three files are changed:

```
change C:\Project\chokidar-bug\test.js
change C:\Project\chokidar-bug\test.jsx
change C:\Project\chokidar-bug\test.jsxy
```

I don't think the behavior is what I expected.

Test in node v4.1.0 & windows 7 64 & chokidar 1.2.0

**Comment by valaxy** [comment] 2015-10-24 12:41
By the way, when I tried `usePolling: false`, it did really fix the problem.
I also found a similar situation https://github.com/paulmillr/chokidar/issues/296

**Comment by es128** [comment] 2015-10-26 14:36
Yes, this is a dupe of #296, and the situation remains the same as [when I said](https://github.com/paulmillr/chokidar/issues/296#issuecomment-121680171) that I don't see how to second-guess the system-level events in order to make it better. `add` and `unlink` events I can do things to double check what's actually there, but I have less options for validating a `change`.

If anyone has any ideas, let me know in the linked thread.

Closing this one as a dupe.

**Closed by es128** 2015-10-26 14:36 UTC
