### ISSUE TITLE
Watching grand parent folder don't work

### ISSUE THREAD

**Issue by Plou** [paulmillr/chokidar#339] opened 2015-08-18 15:14 UTC
Hi,
I tried to watch to watch files up in the file's tree but it don't seems to work. I can only go up on level

- `../img/*` works fine
- `../../img/*` don't

Any ideas ?

I first posted this issue here: BrowserSync/grunt-browser-sync/issues/118

**Comment by es128** [comment] 2015-08-18 16:03
Works fine for me. Are you sure there are files at `../../img/`? 

Perhaps you want to make use of the `cwd` option.

Closing the issue for now. If you can provide better evidence or a reproducible case of the issue you're experiencing, will reopen.

**Closed by es128** 2015-08-18 16:03 UTC

**Comment by Plou** [comment] 2015-08-19 08:29
I found where the problem came from ^^.

The regex to ignore dotfiles shared in the read me (used by  BrowserSync/grunt-browser-sync) match any occurence of `/.` which is found in `../../`

I made this regex which seems to works better: `{ ignored: /^([.][^.\/\\])|([\/\\]+[.][^.])/ }`

Would you like me to do a pull request to update the read me. Is there other places where the regex is used ?

**Comment by es128** [comment] 2015-08-19 11:54
Chokidar does not have a default value for `ignored`, and the readme example does work for watching the current directory. I suppose we could update it to something that will cause less confusion, but the example you came up with seems too dense for a simple example. 

What about `/\.[^\\\/]+$/`? Does it work as intended for your use case?

**Comment by Plou** [comment] 2015-08-19 12:26
It will match all files with an extension. This one only match dotfiles in the current directory but don't detect relative path  `/^([.][^.\/\\])/` : 
- `./.fail`
- `.match`

Another way around the problem could be to be more specific in the comment or to change the example.
Something like that, easier to understand and sure to cover use cases :

``` javascript
// One-liner for current directory, ignores text files
chokidar.watch('.', {ignored: /[.]txt$/}).on('all', function(event, path) {
  console.log(event, path);
});


var watcher = chokidar.watch('file, dir, or glob', {
  ignored: /[.]txt$/,
  persistent: true
});

```

**Comment by es128** [comment] 2015-08-19 12:29
Ok yeah I like the simpler example. Will change it to something like that.
