### ISSUE TITLE
Either watchpack or chokidar is locking files in Windows

### ISSUE THREAD

**Issue by DullReferenceException** [paulmillr/chokidar#446] opened 2016-03-05 00:53 UTC
I'm indirectly using `chokidar` through `watchpack`. File watching appears to be causing files to be locked in Windows. For example, if I'm running the dev webpack server and do an `npm install` or `git rebase`, their attempts to update or delete files sometimes receive access permission errors.

My issue was originally filed with `watchpack`, but it was closed because file watching is implemented through `chokidar`. But I'm not sure whether the bug is in `chokidar` or in the way it is being used. Here's how `watchpack` is using `chokidar`.

https://github.com/webpack/watchpack/blob/master/lib/DirectoryWatcher.js#L48

Is it possible that `chokidar` is opening files/directories in an overly-restrictive manner? As far as I can tell, OS X developers on my team do not have this same issue.

**Comment by paulmillr** [comment] 2016-03-06 00:23
> Is it possible that chokidar is opening files/directories in an overly-restrictive manner

That's unlikely. I think that's watchpack-related.

**Comment by Elephant-Vessel** [comment] 2016-03-06 10:24
This is probably why: https://github.com/paulmillr/chokidar/issues/320?

**Comment by es128** [comment] 2016-03-07 15:05
> Is it possible that chokidar is opening files/directories in an overly-restrictive manner?

No, not in terms of anything chokidar has control over. Try using chokidar in isolation (without watchpack) to see if you can reproduce the issue. You could start with the example.js script in the repo. If it does occur just from watching with chokidar, then the issue is somewhere in the realm of node.js core `fs.watch()` or the Windows file system itself. You might be able to work around it with the `usePolling: true` option. Either way, there's nothing we can do in chokidar to have an impact afaik, so I'll be closing the issue. But PR welcome if anyone can propose a solution.

**Closed by es128** 2016-03-07 15:05 UTC
