### ISSUE TITLE
Node doesn't exit after closing watch

### ISSUE THREAD

**Issue by EzraM** [paulmillr/chokidar#434] opened 2016-02-02 03:37 UTC
After setting up, then closing, a watcher, the Node process doesn't exit.
Windows.

``` javascript
const chokidar = require('chokidar')
const options = {}
const directoryPath = srcPath
// configuration taken from webpack
const watcher = chokidar.watch(directoryPath, {
    ignoreInitial: true,
    persistent: true,
    followSymlinks: false,
    depth: 0,
    atomic: false,
    alwaysStat: true,
    ignorePermissionErrors: true,
    usePolling: options.poll ? true : undefined,
    interval: typeof options.poll === "number" ? options.poll : undefined
});
watcher.close()
```

**Comment by nicokaiser** [comment] 2016-02-18 15:53
Maybe this has something to do with nested directories. We observed this with deep directories, but it worked with flat ones without subdirectories.

**Comment by DarkPark** [comment] 2016-02-27 15:39
I confirm the problem. No nested directories are required.
A simple code to reproduce: 

```js
var chokidar = require('chokidar');

var fn = function ( name ) {
    console.log('change: ' + name);
};

var watcher = chokidar.watch('./*')
    .on('change', fn)
    .on('unlink', fn)
    .on('add',    fn);

setTimeout(function () {
    console.log('should exit!');
    watcher.close();
}, 10000);
```

Interesting point to note - just run the code above and wait doing nothing - it will exit the node process in 10 seconds without any problems.
It will NOT exit in case there will be some file modifications in the current dir before `watcher.close`. So even once change/unlink/add are triggered and this hangs the process.

**Comment by eoinmurray** [comment] 2016-06-15 13:14
Same issue here -> quite important for us because we need many watchers to be opened and closed in a long running program, and close locks of the program

**Comment by eoinmurray** [comment] 2016-06-16 19:01
Its the `FSWatcher.unwatch` which is hanging, and I think this is being called inside `FSWatcher.close` 

```javascript
    watchers.forEach((w)=>{
      console.log(`unwatching ${watchers.length}`)
      const watched = keys(w.getWatched())
      console.log('gotWatched()')
      w.unwatch(watched)
      console.log('unwatched')
    })
  })
```

Fails sometimes on the `w.unwatch` step

**Comment by es128** [comment] 2016-06-16 19:12
Unfortunately it is most likely an issue with the underlying watch methods. I don't have high confidence that this is something that is possible to fix from within chokidar. Also likely to be highly OS-dependent. Would appreciate if anyone reporting this issue would note their OS & node version.

I would guess it's core's [`fs.FSWatcher#close()`](https://nodejs.org/dist/latest-v4.x/docs/api/fs.html#fs_watcher_close) that's really where the problem occurs. Is anyone who is observing this issue on OS X and using fsevents?

If this is critical, try using `usePolling: true` and seeing what impact that has. May solve this problem, but there will be performance tradeoffs.

**Comment by philkunz** [comment] 2016-09-22 14:25
any ETA on this one?

**Comment by es128** [comment] 2016-09-22 14:30
Not from my side. Nobody who can reproduce this issue has provided any of the feedback I asked for to help diagnose the problem. 

I have not been able to reproduce/observe the problem myself. It seems system-dependent, and as stated before, I'm not confident that once we do figure out the source that there's something chokidar could do differently to impact the outcome.

**Comment by philkunz** [comment] 2016-09-22 14:40
here is a reproducible build: The memory event leak on top is due the current npm version and is not the source of the problem + different process

https://gitlab.com/pushrocks/smartchok/builds/4332135

**Comment by philkunz** [comment] 2016-09-22 14:48
ok, I think I found the problem... If I add the same file twice (look at the Smartchok.add() method) then chokidar doesn't close correctly. Does chokidar test internally, if the file is already watched/has been added before?

**Comment by es128** [comment] 2016-09-22 14:55
Yes.

https://github.com/paulmillr/chokidar/blob/master/lib/nodefs-handler.js#L251-L252

**Comment by es128** [comment] 2016-09-22 14:55
But you might be onto something in terms of watch handles somehow getting lost

**Comment by philkunz** [comment] 2016-09-22 15:16
This commit fixed it for me: https://gitlab.com/pushrocks/smartchok/commit/0fe26b4b44f017dc2c06da618742bcbd46ca71b1

I'm only making sure only to add a path string once. If I have more findings I'll post here.

**Comment by russokj** [comment] 2016-09-23 00:07
Here's another example of chokidar causing the application to hang.  In this example, the app will listen to a file named 'tmp.change' in the local directory and print the events that occur on that file.  If the file is ever modified to have the content be 'exit\n', then the app should exit.  Normally this works, but if the file already exists with the exit string in it when the app is started, the 'Exiting...' message is printed, but the app doesn't exit.

```javascript
'use strict';

const chokidar = require('chokidar');
const fs = require('fs');


let watcher = chokidar.watch('tmp.change', {})
watcher.on('all', (event, path) => { processEvent(event,path); });

function processEvent(event, path) {
  if (event === 'change' || event === 'add') {
    let content = fs.readFileSync('tmp.change', 'ascii');
    console.log(event, path, content);

    if (content === 'exit\n') {
      console.log("Exiting ...");
      watcher.close();
      watcher = null;
    }
  } else {
    console.log(event, path);
  }
}

if (watcher) {
  console.log("Watcher is running ... ");
}
```

**Comment by es128** [comment] 2016-09-23 19:13
@russokj if you modify your example to ensure that the `ready` event has been fired prior to calling `watcher.close()` then it will exit every time. I'm not sure how informative this is for the other people that have reported this issue, but I think it's debatable that the race condition you've designed in this example should be considered a chokidar bug. That said, it would be possible to solve for it by being more `ready`-aware inside of `FSWatcher.prototype.close`.

**Comment by philkunz** [comment] 2016-09-23 19:18
@es128 @russokj  smartchok takes care of preventing this race condition by making smartchok.stop() (which is wrapping watcher.close) itself async.

**Comment by es128** [comment] 2016-09-23 19:20
@philkunz if you feel like contributing directly to chokidar rather than (or in addition to) putting out your wrapper, I'd be happy to review your PRs.

**Comment by philkunz** [comment] 2016-09-23 19:29
@es128 ... I feel that chokidar kind of has its own logic + it is written in JS, not in TypeScript... A possibility would be to transfer chokidar to TypeScript, have typings autogenerated, and maybe add the smartchok class (which is rather small) as additional approach to prevent breaking changes.

**Comment by es128** [comment] 2016-09-23 19:30
Well no, I'm not suggesting that kind of overhaul. Just saying if you want to make direct incremental improvements to chokidar, the door is open.

**Comment by rasenplanscher** [comment] 2016-11-18 13:18
I ran into this today using node v6.7.0 on Windows 7. I tried `usePolling: true` but it made using globs with '**' unusable and, more importantly, did not fix the issue.

Any ideas as to what else I might try?

**Comment by es128** [comment] 2016-11-18 15:10
See if you can reproduce it with a small watch footprint, like just a few files in one or two dirs. If not, see if you can pinpoint what conditions introduce the problem.

**Comment by rasenplanscher** [comment] 2016-11-18 19:34
I have setup a minimal project for testing here: https://github.com/rasenplanscher/test-gulp.watch.close

Just `npm install` and `npm install -g gulp`, then you're good to go. 

On my machine these will just hang there:
- `node chokidar-event.js` does not use polling
- `node chokidar-poll.js` uses polling
- `gulp` is how I was using this, with gulp

On the other hand, these two, waiting for the `ready` event, work:
- `node chokidar-afterReady.js`
- `gulp works`

In my more complex use case, I didn't see that... I'll dig deeper into it and report back what I find.

**Comment by rasenplanscher** [comment] 2016-11-18 20:03
I found my issue: the software that generates the files I'm watching does not write them in a queue as I thought, but rather dumps them all at once (maybe by moving a temp directory). So, watching is useless in my case, I am better off just waiting for the load to drop...

However, I think my little test shows that the only issue with chokidar itself is the `ready`-awareness of `close()`, as you have already suspected.

**Comment by majgis** [comment] 2017-02-13 21:03
Node.js v6.9.5
chokidar v1.6.1
Ubuntu 16.04.1 LTS

I tried waiting for the 'ready' event before closing, as well as setting a long timeout, but it did not solve the problem.

**Comment by rasenplanscher** [comment] 2017-02-14 08:52
@majgis Have you tried my minimal setup, do you have the issue there as well? What's the minimal use case that fails for you?

**Comment by EzraM** [comment] 2017-02-14 12:52
Posted a repo with a few files and some notes:
https://github.com/EzraM/chokidar-close-watch-434

Background on the use case: we'd wrapped chokidar in an Rx Observable to model our build process as a stream. Sometimes, the stream would close pretty soon after opening. Our workaround was to exit the process if we needed it to close.

Worth noting, on OS X 10.11, if you wait for >20ms, the watcher will close and not hang.

**Comment by es128** [comment] 2017-02-14 15:57
@EzraM instead of using `setTimeout` with a magic number you can just ensure the `ready` event has fired prior to trying to call `watcher.close()`. The `.close()` method does not abort the in-progress work that is happening within chokidar prior to the `ready` event firing, so new watch bindings keep being created. Read the thread for more details.

```js
watcher.on('ready', watcher.close)
```

**Comment by rasenplanscher** [comment] 2017-02-14 16:10
I just wanted to suggest the same as @es128 but, just to be sure, I plugged the `on('ready')` into a timeout, and it actually does not work 🙁 

See `afterReadyAfterTimeout.js` in [my test repo](https://github.com/rasenplanscher/test-gulp.watch.close)

**Comment by es128** [comment] 2017-02-14 16:30
Why are you wrapping it in the timeout? The `ready` event fired already before you bound the listener.

**Comment by rasenplanscher** [comment] 2017-02-14 16:55
You are spot-on and I was not aware of that fact until a few minutes ago.

The timeout simulates the situation when `watcher.close` is called after the watcher has been working for some time. I don't think a watcher that is closed immediately after generation is actually useful, so we should talk about a situation in which the watcher has been working for an unknown amount of time. After all, only then will we even have a race condition.

As it stands, if one wants to close the watcher, they need to either check `watcher._readyEmitted`, which seems dirty, or do `watcher.on('ready', watcher.close) && watcher.close()`, which looks a little less dirty 🤔

**Comment by es128** [comment] 2017-02-14 16:59
I don't think the second suggestion will work in many cases. Something like this should do it reliably:

```js
watcher._readyEmitted ? watcher.close() : watcher.on('ready', watcher.close)
```

**Comment by rasenplanscher** [comment] 2017-02-14 17:13
Just to be clear: many projects use underscore-prefixed names to denote intended-to-be-private members, is this the case here? That would make the work-around with `_readyEmitted` just a band-aid, to be scrapped as soon as feasible.

On the other hand, I checked and as you thought, it doesn't really work 🙁

**Comment by es128** [comment] 2017-02-14 17:19
Yes, it's intended to be a "private" property, definitely shouldn't be written over, but it will serve this purpose at this point. Ideally, `.close()` will be properly fixed eventually to prevent the need for workarounds.

If you really want to avoid using it you can make your own:

```js
var readyEmitted = false
watcher.on('ready', function() { readyEmitted = true })
```

**Closed** 2017-05-02 15:48 UTC
Labels: bug
