### ISSUE TITLE
Events lost with awaitWriteFinish

### ISSUE THREAD

**Issue by nono** [paulmillr/chokidar#384] opened 2015-11-03 15:52 UTC
Hi,

on node 0.10 or 0.12 and linux, with this program:

```coffee
#!/usr/bin/env coffee

chokidar = require 'chokidar'
path = require 'path'

watcher = chokidar.watch '.',
    cwd: path.resolve '.'
    atomic: true
    awaitWriteFinish:
        pollInterval: 100
        stabilityThreshold: 2000
    interval: 1000
    binaryInterval: 2000

watcher.on 'add', (file) ->
    console.log "#{file} was added"

watcher.on 'raw', (event) ->
    console.log 'raw', event
```

If I do these commands:

```
$ cp ~/Desktop/happycloud.png .
$ rm happycloud.png            
$ cp ~/Desktop/happycloud.png .
$ rm happycloud.png            
$ cp ~/Desktop/happycloud.png .          
$ rm happycloud.png            
$ cp ~/Desktop/happycloud.png .
$ rm happycloud.png            
$ cp ~/Desktop/happycloud.png .
$ rm happycloud.png            
$ cp ~/Desktop/happycloud.png .
```

The first events are reported, but after some time, only the raw events are fired:

```
[...]
happycloud.png was added
raw rename
raw rename
raw change
happycloud.png was added
raw rename
raw rename
raw change
happycloud.png was added
raw rename
raw rename
raw change
raw change
raw change
raw change
happycloud.png was added
raw rename
raw rename
raw change
raw rename
raw rename
raw change
raw rename
raw rename
raw change
raw rename
raw rename
raw change
raw rename
raw rename
raw change
```

**Comment by nono** [comment] 2015-11-03 16:37
It happens if I remove the file in the 2s after copying it (stabilityThreshold). Then, `this._pendingWrites` has an entry for `happycloud.png` and blocks all events here: https://github.com/paulmillr/chokidar/blob/master/index.js#L127

**Comment by es128** [comment] 2015-11-03 17:59
My quickie attempt at a fix for this didn't pan out.

@alexpusch would appreciate if you could take a look

**Comment by alexpusch** [comment] 2015-11-03 21:15
By design, when awaitWriteFinish is activated the 'add' event is held back until the file is fully written. If the file is deleted during the writing process, no event will be raised. In such case there is no 'add' event so it's illogical to raise an 'unlink' event.

**Comment by es128** [comment] 2015-11-03 21:18
@nono if the last action taken is to copy the file, does the `add` event appear?

**Comment by nono** [comment] 2015-11-04 08:33
@es128 exactly, in the last action, the `add` is not fired.

@alexpusch yes, but it should not block later events for the same path.

Maybe it's more clear with this sequence:

```
$ cp ~/Desktop/happycloud.png . ; rm happycloud.png ; sleep 3 ; cp ~/Desktop/happycloud.png .
```

The file is present at the end, but no `add` event is fired for this file. The first one is canceled by awaitWriteFinish, but it's a bug for the second copy.

I've added a console.log(this.options.awaitWriteFinish); just before https://github.com/paulmillr/chokidar/blob/master/index.js#L127 and it still has an entry for `happycloud.png` after the `rm`.

**Comment by nono** [comment] 2015-11-04 13:47
@es128 with your changes from #385, it fires a `change` event, but not the `add` event. But, with only part of your changes (#388), it's fixed. Thanks for your help!

**Closed** 2015-11-04 15:23 UTC
