### ISSUE TITLE
ready never emitted when globs contains non-existing dir?

### ISSUE THREAD

**Issue by evgenyt1** [paulmillr/chokidar#449] opened 2016-03-12 20:02 UTC
```
chokidar.watch([
        './node_modules/**',
        './vendor/**',
        './**/*.html',
        './**/*.+(jpg|png|svg)'
], { cwd: appDir}).on('ready', () => {console.log('ready');});
```

In my case 'vendor' doesn't exist. And I never get 'ready' until I comment out it.

**Comment by ijliebemij** [comment] 2016-04-22 15:59
Same happens when there are duplicates passed in the array of paths.

**Comment by Oikio** [comment] 2016-05-28 11:01
Same here, it happens only when cwd option is set.

**Comment by UltCombo** [comment] 2016-06-20 11:28
I've noticed this issue while writing tests for gulp-watch, can still reproduce the problem in the latest version.

**Comment by es128** [comment] 2016-06-20 13:06
@UltCombo yes, it hasn't been addressed yet. There's a bug in the logic for keeping track of whether all the watch paths have been traversed. When nothing is found for a glob, the iterators end up out of sync.

**Comment by laggingreflex** [comment] 2016-12-04 02:56
>Same happens when there are duplicates passed in the array of paths.

@vdiez That sounds more like #561 but it too exhibits this behavior, i.e. not fire ready event.

>Same here, it happens only when cwd option is set.

#561 happens even without cwd option

**Comment by wmertens** [comment] 2017-11-14 14:59
Is this fixed now? I mean, I'm using a single glob like `'/path/{dir1,dir2,dir3}/**/*'` and I'm getting a `ready` event even though `dir2` doesn't exist. Or is it because it is a singular glob?

**Comment by laggingreflex** [comment] 2018-08-14 09:43
Here's a [repro](https://github.com/laggingreflex/repro-chokidar-never-close) (it was for another issue https://github.com/paulmillr/chokidar/issues/688#issuecomment-412746054 but reproduces this as well - i.e. 'ready' not firing)

**Comment by paulmillr** [comment] 2019-08-13 16:38
Update to v3, it should resolve this.

**Closed by paulmillr** 2019-08-13 16:38 UTC
Labels: bug
