### ISSUE TITLE
chokidar doesn't notice changes under weird path

### ISSUE THREAD

**Issue by ariovistus** [paulmillr/chokidar#336] opened 2015-08-14 21:45 UTC
In windows 7 I attempt to run the following script:

```
chokidar = require('chokidar')
fs = require('fs')

path = "APCS (3.0)2\\burrito.txt"
console.info(fs.lstatSync(path)) # path exists
watcher = chokidar.watch(path)
watcher.on('change', (path) -> console.info("path: #{path} changed"))

setTimeout(( -> 1), 50000)
```

chokidar never notices file changes to burrito.txt.

**Comment by es128** [comment] 2015-08-14 22:09
likely a dupe of #300

**Closed by es128** 2015-08-14 22:09 UTC
