### ISSUE TITLE
How to watch with brackets in dirname (possibly bug)

### ISSUE THREAD

**Issue by remy** [paulmillr/chokidar#372] opened 2015-10-18 21:11 UTC
Trying to watch the contents of a dir with brackets in the filename doesn't seem to work:

```js
var chokidar = require('chokidar');

var fs = require('fs');
try {
  fs.mkdirSync('just a (demo)');
  fs.writeFileSync('just a (demo)/foo.js');
} catch (e) {
  // did it already
}

var watcher = chokidar.watch('just a (demo)');
watcher.on('add', function (f) { console.log(f); });
```

Yields no results. Removing the brackets in the dirname then works as expected. I tried all manner of escaping but couldn't get anything to work.

Related: https://github.com/remy/nodemon/issues/655

Am I matching wrong, is there an escape method or is this a real bug?

**Comment by TrySound** [comment] 2015-10-18 21:16
@remy Parentheses are used in [globs](https://github.com/jonschlinkert/micromatch#features)

**Comment by remy** [comment] 2015-10-18 21:26
Hmm. I appreciate that, but the path *does* have a bracket in it.

I've managed to track it down to when fsevents-handler.js [here](https://github.com/paulmillr/chokidar/blob/master/lib/fsevents-handler.js#L301-L303) knows that `stat.isDirectory()` is `true` but because of a false positive on `!isglob(path)` [here](https://github.com/paulmillr/chokidar/blob/master/index.js#L321), the `add` event isn't emitted. 

I've not worked out yet whether this is _just_ the event or if that the entire directory is being ignored by Chokidar, but I suspect the later.

**Comment by es128** [comment] 2015-10-19 01:08
Closing as dupe of #300

I'm pretty sure I know what the solution to this ought to be. Just haven't had time to work on implementing it yet.

**Closed by es128** 2015-10-19 01:08 UTC

**Comment by remy** [comment] 2015-10-19 06:10
I'd be prepared to take a shot at the PR but I just wanted to ask if there was a specific reason why when fsevents-handler knows the `stat` is a directory, does it then do a sanity check against whether it's a glob?

**Comment by es128** [comment] 2015-10-19 14:12
Off the top of my head I would have thought the glob check was done before a `stat`, but if what you're saying is the case then it's probably just an oversight or an accident of history. And it should make it easier to resolve the issue than I had expected. A similar issue was solved for filenames somewhere along the way, perhaps the current state of the code is related to that.

If you're going to work on a PR, please start with a failing test similar to https://github.com/paulmillr/chokidar/blob/5e02fa945c339d3c80ff544dfb7d5220c12b0aa6/test.js#L534. And recognize that it needs to be solved in all watch modes, so if you're fixing something in fsevents-handler, something similar will probably need to be done in nodefs-handler as well.

**Comment by remy** [comment] 2015-10-19 15:02
@es128 yeah, understood. I take the same approach for PRs on nodemon. If I've got time this week, I'll put it together, I've spelunked the code enough to see how I'd fix it (though I'm not familiar with your test suite yet...but hey, it's just JavaScript right...lastwords...)

**Comment by es128** [comment] 2015-10-19 15:22
Well yeah the test suite here can be really annoying at times because reasons, although writing the test itself should be fairly straightforward based on existing examples. Feel free to reach out for help/advice if it ends up getting in your way.

Totally ok to get a PR startedvwith less than a complete solution - it still likely helps.
