### ISSUE TITLE
Chokidar 3.1.1 no longer react to file changes

### ISSUE THREAD

**Issue by ryanelian** [paulmillr/chokidar#888] opened 2019-09-20 21:45 UTC
**Describe the bug**
 I am using code like this:

```ts
        watch(this.finder.scssGlob, {
            ignoreInitial: true
        })
            .on('add', file => {
                file = upath.toUnix(file);
                Shout.sass(chalk.grey('tracking new file:', file));
                debounce();
            })
            .on('change', file => {
                file = upath.toUnix(file);
                Shout.sass(chalk.grey('updating file:', file));
                debounce();
            })
            .on('unlink', file => {
                file = upath.toUnix(file);
                Shout.sass(chalk.grey('removing file:', file));
                debounce();
            });
```

```ts
        watch(this.sourceStore.typeCheckGlobs, {
            ignoreInitial: true
        })
            .on('add', (file: string) => {
                this.sourceStore.loadFile(file).then(changed => {
                    Shout.typescript(chalk.grey('tracking new file:', file));
                    debounce();
                });
            })
            .on('change', (file: string) => {
                this.sourceStore.loadFile(file).then(changed => {
                    if (changed) {
                        Shout.typescript(chalk.grey('updating file:', file));
                        debounce();
                    }
                });
            })
            .on('unlink', (file: string) => {
                let deleted = this.sourceStore.removeFile(file);
                if (deleted) {
                    Shout.typescript(chalk.grey('removing file:', file));
                    debounce();
                }
            });
```

The glob pattern is something like this:

```ts
    /**
     * /project/client/css/\*\*\/*.scss
     */
    get scssGlob(): string {
        return upath.join(this.cssInputFolder, '**', '*.scss');
    }
```

```ts
    get typeCheckGlobs() {
        return this._typeCheckGlobs;
    }

        let tsGlobs = upath.join(folder, '**', '*.ts');
        let tsxGlobs = upath.join(folder, '**', '*.tsx');
        let vueGlobs = upath.join(folder, '**', '*.vue');
```

The chokidar event no longer fires. Version 3.0.2 works just fine.

**Versions (please complete the following information):**
 - Chokidar version 3.1.1
 - Node version 12.9.1
 - OS version: Windows 10 1903 Build 18362.365

**To Reproduce**

Use something like above code / glob to detect file changes.

**Expected behavior**

File change triggers.

**Additional context**

EDIT: off-topic, just realized this issue number is 888. lucky? 😄

**Comment by paulmillr** [comment] 2019-09-21 09:30
Please try it with chokidar 3.1.0, not 3.1.1.

**Comment by ryanelian** [comment] 2019-09-21 09:40
Just now, confirmed that 3.1.0 work:

![image](https://user-images.githubusercontent.com/8892187/65371520-6d603880-dc8e-11e9-99bf-9a5f012fdf3c.png)

But 3.1.1 does not... (Also re-checked just now)

![image](https://user-images.githubusercontent.com/8892187/65371481-1c504480-dc8e-11e9-9a2a-5640ba4cb803.png)

**Comment by paulmillr** [comment] 2019-09-23 18:37
I think you're using wrong globs or something like that. We've changed path handling in 3.1.1. Will investigate.

**Comment by ryanelian** [comment] 2019-09-23 19:30
In all above examples, I am using blob string: `/something/like/this/**/*.ext` (without backslash thanks to upath library)

What would be the proper blob string for cases like that then?

**Comment by frigus02** [comment] 2019-09-23 19:38
I can reproduce the issue on Windows 10 with Node v12.10.0 with the [example.js](https://github.com/paulmillr/chokidar/blob/31fd30afa4aaa7cbfa1d6172707da1f31b867223/example.js) from the repo. I changed to first line to

```js
global.watcher = require('./').watch('./lib/*.js', {
```

Then I ran `node .\example.js` and changed any file in the lib folder. This is the full output (no changes logged):

```
C:\code\chokidar> node .\example.js
Ready
```

I played a bit around. When I change the following line to use `normalizePathToUnix` to instead of `sysPath.normalize`:

https://github.com/paulmillr/chokidar/blob/31fd30afa4aaa7cbfa1d6172707da1f31b867223/index.js#L359

And try the example again, it seems to work:

```
C:\code\chokidar> node .\example.js
add lib\fsevents-handler.js
add lib\nodefs-handler.js
Ready
change lib\nodefs-handler.js
```

If you think this fix is acceptable, I'm happy to submit a PR for it.

Would be great to have a test for this as well, but I had trouble getting the tests to run properly on Windows. Are there any known issues here?

**Comment by frigus02** [comment] 2019-09-25 21:17
I looked a bit more into this. Using `normalizePathToUnix` does solve the issue for globs. But it changes the behavior for other tests slightly.

- Before, when you watch a path like `C:\files\todo.txt`, chokidar emits change events for `C:\files\todo.txt`. 
- With `normalizePathToUnix`, when you watch a path like `C:\files\todo.txt`, chokidar emits change events for `C:/files/todo.txt`.

See here, which tests would be affected by the change: https://github.com/paulmillr/chokidar/compare/master...frigus02:fix-watching-windows. Notice that I also had to normalize paths in `unwatch`, otherwise paths wouldn't match.

I'm not sure what the best course of action here is. I don't fully understand the issue #871, which was fixed by normalizing paths. Normalizing paths does not fix the "Expected pattern to be a non-empty string" error for me. I can still reproduce that with a path like `./` on both Windows and Linux. I'm however unable to reproduce the issue with a path like `./package.json`, even without normalizing paths.

I wonder if the issue #871 has been fixed by something else and we can just revert the change here and not normalize paths. I feel like that's all I can do here. Need @paulmillr's help now 🙂.

**Comment by ryanelian** [comment] 2019-09-28 12:30
I just saw the commits, it seems paulmillr has fixed the issue?
https://github.com/paulmillr/chokidar/commit/048f9350b871f1ca10a8c806ae325be8e1430013


I personally don't mind if the emitted path  become UNIX-like on Windows because I personally use `upath` library to make my app path handling behavior to be UNIX-like with slashes instead of backslashes because I hate hidden surprises when dealing with mixed path and prefer consistency in my codebase.

... But hey, that's just my opinion. 😄

**Comment by paulmillr** [comment] 2019-09-28 14:32
Not really — Still debugging this shit

**Comment by paulmillr** [comment] 2019-09-30 20:10
@ryanelian fixed in master, I think

**Comment by paulmillr** [comment] 2019-09-30 22:13
Could someone test this?

**Closed by paulmillr** 2019-09-30 22:13 UTC
Labels: windows

**Comment by ryanelian** [comment] 2019-09-30 22:30
Sure. 

I tried using `yarn add https://github.com/paulmillr/chokidar.git` in my compiler tool project.

Looks like it's working on Windows. Haven't tested on other platforms.

**Comment by paulmillr** [comment] 2019-09-30 22:44
@countnazgul how's your project doing?

**Comment by XhmikosR** [comment] 2019-10-01 07:14
@paulmillr it seems it's working again.

**Comment by countnazgul** [comment] 2019-10-01 09:59
@paulmillr just tested with v3.2.0 and it seems to work nicely! Thanks for the quick response!
