### ISSUE TITLE
watch not exist file,Become monitor all

### ISSUE THREAD

**Issue by WzFFzW** [paulmillr/chokidar#1015] opened 2020-06-30 14:11 UTC
**Describe the bug**
code:
```
chokidar.watch('notExist.js').on('raw', (event, path, details) => {
  console.log('Raw event info:', path);
});
```
watch a file of not exist,  the behavior will like  
> chokidar.watch('.').on('raw', () => {});

only raw event has problem
**Versions (please complete the following information):**
 - Chokidar version: 3.4.0
 - Node version: 12.16.0
 - OS version: window10

**To Reproduce:**

```
chokidar.watch('notExist.js').on('raw', (event, path, details) => {
  console.log('Raw event info:', path);
});
```

**Expected behavior**
raw event not emit

**Comment by paulmillr** [comment] 2020-06-30 14:52
duplicate of #872

**Closed by paulmillr** 2020-06-30 14:52 UTC
