### ISSUE TITLE
Error after last release

### ISSUE THREAD

**Issue by Fer0x** [paulmillr/chokidar#274] opened 2015-04-08 15:02 UTC
```
./node_modules/.bin/brunch build --production

08 Apr 14:53:23 - [32minfo[0m: compiled 122 files into 3 files, copied 486 in 10271ms

/project/node_modules/brunch/node_modules/chokidar/index.js:453
    this._closers[watchPath]();
                            ^
TypeError: Property 'app' of object object is not a function
  at EventEmitter.<anonymous> (/project/node_modules/brunch/node_modules/chokidar/index.js:453:29)
  at Array.forEach (native)
  at EventEmitter.FSWatcher.close (/project/node_modules/brunch/node_modules/chokidar/index.js:452:30)
  at writeCb (/project/node_modules/brunch/lib/watch.js:342:17)
  at /project/node_modules/brunch/lib/fs_utils/write.js:156:12
  at /project/node_modules/brunch/node_modules/async-each/index.js:24:44
  at /project/node_modules/brunch/lib/fs_utils/generate.js:205:16
  at /project/node_modules/brunch/lib/fs_utils/common.js:36:16
  at /project/node_modules/brunch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:104:5
  at Object.oncomplete (fs.js:107:15)

npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by es128** [comment] 2015-04-08 17:06
dupe of https://github.com/brunch/brunch/issues/956

**Closed by es128** 2015-04-08 17:06 UTC
